services:
  eleven_front:
    container_name: eleven-front
    build:
      context: .
      dockerfile: Dockerfile
      args: 
       - SERVICE_ID=${SERVICE_ID}
       - TEMPLATE_ID=${TEMPLATE_ID}
       - PUBLIC_KEY=${PUBLIC_KEY}
    restart: always
    ports:
        - 3001:3001
