name: Create And Deploy Docker Image For eleven-front
on:
   push:
      branches:
         - main
jobs:
   build:
      runs-on: ubuntu-latest
      env:
         SERVICE_ID: ${{ vars.SERVICE_ID }}
         TEMPLATE_ID: ${{ vars.TEMPLATE_ID }}
         PUBLIC_KEY: ${{ vars.PUBLIC_KEY }}
      steps:
         - name: Login to Docker Hub
           uses: docker/login-action@v3
           with:
              username: ${{ vars.DOCKER_USERNAME }}
              password: ${{ secrets.DOCKERHUB_TOKEN }}

         - name: Checkout code
           uses: actions/checkout@v4
           with:
              fetch-depth: 0

         - name: Set up QEMU
           uses: docker/setup-qemu-action@v3

         - name: Set up Docker Buildx
           uses: docker/setup-buildx-action@v3

         - name: Build And Push
           uses: docker/build-push-action@v6
           with:
              push: true
              file: Dockerfile
              tags: ${{ vars.DOCKER_USERNAME }}/${{ github.event.repository.name }}:latest
              build-args: |
                 SERVICE_ID=${{ env.SERVICE_ID }}
                 TEMPLATE_ID${{ env.TEMPLATE_ID }}
                 PUBLIC_KEY=${{ env.PUBLIC_KEY}}

   deploy:
      runs-on: ubuntu-latest
      needs: build
      steps:
         - name: Set up SSH
           run: |
              mkdir -p ~/.ssh
              echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
              chmod 600 ~/.ssh/id_rsa
              ssh-keyscan -p 22 -t rsa ${{ secrets.SERVER_HOST }} >> ~/.ssh/known_hosts
              chmod 600 ~/.ssh/known_hosts

         - name: Load Docker image and restart docker
           run: |
              ssh -o StrictHostKeyChecking=yes -T ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }}  <<EOF

              echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login \
                --username "${{ vars.DOCKER_USERNAME }}" \
                --password-stdin

              docker compose -f eleven-compose.yaml pull eleven-client

              docker compose -f eleven-compose.yaml up eleven-client --force-recreate -d

              docker image prune -f
              EOF
